# Generated by Django 3.0.3 on 2020-02-20 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0003_fishermanblogpage_fishermangallery_fishermanindexpage_tramuntanablogpage_tramuntanagallery_tramuntan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramuntanaindexpage',
            name='route_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
